#ifndef GEOMATHEMATICS_GLOBAL_H
#define GEOMATHEMATICS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GEOMATHEMATICSLIBRARY)
#  define GEOMATHEMATICS_EXPORT Q_DECL_EXPORT
#else
#  define GEOMATHEMATICS_EXPORT Q_DECL_IMPORT
#endif

#endif // GEOMATHEMATICS_GLOBAL_H
